---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: check-git-author
  name: Check git authors
  description: Check that GIT_AUTHOR is correctly setup
  language: script
  entry: pre_commit_hooks/check-git-author
  pass_filenames: false
  args:
    - -s
